---
- name: Get package facts
  ansible.builtin.package_facts:

- name: Add exception to the firewall
  when: "'firewalld' in ansible_facts.packages"
  block:
    - name: Set ports
      become: true
      ansible.posix.firewalld:
        port: "{{ zj_rule_details }}"
        permanent: true
        state: enabled
      loop:
        - 80/tcp
        - 443/tcp
        - 5353/udp
      loop_control:
        loop_var: zj_rule_details

    - name: Add exception to source - 10.42.0.0
      become: true
      ansible.posix.firewalld:
        source: 10.42.0.0/16
        zone: trusted
        permanent: true
        state: enabled

    - name: Add exception to source - 169.254.169.251.1
      become: true
      ansible.posix.firewalld:
        source: 169.254.169.1/32
        zone: trusted
        permanent: true
        state: enabled
