---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ fqdn }}"

- name: Install required system packages
  become: true
  ansible.builtin.yum:
    name:
      - iproute-tc
      - git
      - golang
      - python3-cryptography
      - lvm2
    state: present

- name: Add host to the hosts file
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ fqdn }}$"
    line: "{{ ansible_default_ipv4.address }} {{ fqdn }}"
    state: present
