---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ fqdn }}"

- name: Install required system packages
  become: true
  ansible.builtin.yum:
    name:
      - iproute-tc
      - git
      - python3-cryptography
      - lvm2
    state: present

- name: Add host to the hosts file
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ fqdn }}$"
    line: "{{ ansible_default_ipv4.address }} {{ fqdn }}"
    state: present

- name: Create script to get ingress ip address
  become: true
  ansible.builtin.copy:
    src: recognize-iplb-ip-address.sh
    dest: /usr/local/bin/recognize-iplb-ip-address.sh
    mode: "0755"
