---
# Check if pull-secret.txt is available on the host.
# To download secret, https://cloud.redhat.com/openshift/create/local
- name: Fail when openshift_pull_sec not provided
  ansible.builtin.fail:
    msg: "The openshift_pull_secret variable can not be empty!"
  when: not openshift_pull_secret

- name: Copy pull-secret to node
  become: true
  ansible.builtin.copy:
    content: "{{ openshift_pull_secret }}"
    dest: "{{ registry_secret_path }}"
    owner: root
    group: root
    mode: '0600'
  no_log: "{{ hide_sensitive_logs }}"
