---
- name: Get service facts
  ansible.builtin.service_facts:

- name: Stop and disable zram0 device
  become: true
  ansible.builtin.systemd:
    name: dev-zram0.swap
    state: stopped
    enabled: false
  when: "'dev-zram0.swap' in services"

- name: Stop and disable zram-setup process
  become: true
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0.service
    state: stopped
    enabled: false
  when: "'systemd-zram-setup@zram0' in services"

- name: Disable zram
  become: true
  ansible.builtin.shell: |
    swapoff /dev/zram0; zramctl --reset /dev/zram0; zramctl
  register: _swap_status
  failed_when: _swap_status.rc != 0
  changed_when: true

- name: Remove zram packages
  become: true
  ansible.builtin.yum:
    name: zram-generator-defaults
    state: absent

- name: Touch zram-generator conf
  become: true
  ansible.builtin.file:
    path: /etc/systemd/zram-generator.conf
    state: touch
    mode: "0644"

- name: Disable swap
  become: true
  ansible.builtin.shell: |
    # NOTE: yes, ensure twice that the swap is off.
    swapoff -a; swapoff -a
    sed -i '/swap/d' /etc/fstab
  changed_when: true

- name: Check current memory state
  ansible.builtin.command: free -m
  changed_when: false
